sonar.projectKey=cloudnexaa-devsecops
sonar.projectName=Cloudnexaa DevSecOps Pipeline
sonar.projectVersion=1.0.0

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
